# Generated by Django 2.0.7 on 2021-05-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityforecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='visited',
            field=models.CharField(db_index=True, max_length=60),
        ),
    ]
